### ISSUE TITLE
Add to Bioconda

### ISSUE THREAD

**Issue by fellen31** [wdecoster/STRdust#1]
Would be great if STRdust was available on bioconda.

/Felix

**Comment by wdecoster** [comment]
Hi Felix,

Sure, that should be possible. Let me looking into that - do you have occasions when the binary doesn't work?

Wouter

**Comment by fellen31** [comment]
Yes! I'd like to think about replacing TRGT with STRdust for https://github.com/genomic-medicine-sweden/nallo, by adding it as a module to [nf-core](https://nf-co.re). Then conda (& biocontainer) is needed.

**Comment by wdecoster** [comment]
To track my progress - https://github.com/bioconda/bioconda-recipes/pull/47898

(but there appears to be a general issue with the testing on azure)

**Comment by wdecoster** [comment]
I saw this issue is still open, STRdust can be installed with [conda](https://anaconda.org/bioconda/strdust). I need to bump the version though.
