### ISSUE TITLE
Issue running STRdust on a whole genome catalog

### ISSUE THREAD

**Issue by davidlougheed** [wdecoster/STRdust#4]
Hello,
I'm comparing performance/feature-sets of various different STR genotypers right now (full disclosure, this includes [my own](https://github.com/davidlougheed/strkit/)) and I'm encountering panics (presumably one from each thread in this case) when running STRdust in unphased mode.

I think this comes from not having reads for a particular region when allele-clustering is attempted, but I'm not sure.

command:
```
/usr/bin/time -o "./out/calls/${TECH}/${SAMPLE}.strdust.time" ../bin/STRdust \
  -R ./out/adotto_catalog_strkit.bed \
  -s 1 \
  -t 8 \
  --unphased \
  --haploid "${HAPLOID_CHRS}" \
  "${REF}" \
  "${bam_tmpdir}" > "./out/calls/${TECH}/${SAMPLE}.strdust.vcf"
```

output:
```
thread 'thread '<unnamed><unnamed>' panicked at ' panicked at src/phase_insertions.rssrc/phase_insertions.rs::9696::1717:
:
index out of bounds: the len is 0 but the index is 0index out of bounds: the len is 0 but the index is 0

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at src/phase_insertions.rs:96:17:
index out of bounds: the len is 0 but the index is 0
thread '<unnamed>' panicked at src/phase_insertions.rs:96:17:
index out of bounds: the len is 0 but the index is 0
thread '<unnamed>' panicked at src/phase_insertions.rs:96:17:
index out of bounds: the len is 0 but the index is 0
thread '<unnamed>' panicked at src/phase_insertions.rs:96:17:
index out of bounds: the len is 0 but the index is 0

...
```

**Comment by wdecoster** [comment]
Hi David,

Thanks for reporting this; I will try to replicate your issue!


Wouter

**Comment by wdecoster** [comment]
Is this a public dataset that you are using?

**Comment by davidlougheed** [comment]
I'm using an alignment of the reads from https://downloads.pacbcloud.com/public/revio/2022Q4/HG002-rep1/ + a catalog derived from the adotto project (~1.4 million STRs): https://github.com/ACEnglish/adotto 

The precise catalog I'm using is attached (has a 4th column for motif, which I imagine is ignored by STRdust).

[adotto_catalog_strdust.txt.zip](https://github.com/user-attachments/files/16059443/adotto_catalog_strdust.txt.zip)

**Comment by wdecoster** [comment]
Okay, you were correct that this happened when only a single read was present for the genotype, which tripped up the algorithm that attempts to phase it into two haplotypes.  I haven't dealt with such low coverage yet :-)
That should now be fixed. Do you need a binary or will you build from source?

**Comment by davidlougheed** [comment]
I'm building from source, thank you!

**Comment by wdecoster** [comment]
Great, please let me know any other feedback you have :)
