### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by mdanzi** [wdecoster/STRdust#6]
Hi Wouter,

I'm running into some issues compiling STRdust. I'm using Ubuntu 22.04, cargo 1.75.0, and rustup 1.27.1. I make it through most of the compilation process, but end up with this error: 
<code>
Compiling STRdust v0.11.0 (/home/ubuntu/STRdust)
warning: function `create_motif` is never used
 --> src/motif.rs:4:4
  |
4 | fn create_motif(_seq: &str) -> String {
  |    ^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: `STRdust` (bin "STRdust") generated 1 warning
    Finished release [optimized] target(s) in 4.25s
</code>

Initially, it suggested that I run `cargo fix --bin "STRdust"`, but that didn't change anything. 

Let me know if you need any more information from me to debug the problem! 

I was not able to use the pre-compiled binary you provide in the releases section because I am running into the same issue as #4 and it seems your update to fix that was prior to the most recent binary release.  

Best,
Matt

**Comment by wdecoster** [comment]
Hi Matt,

Seems the compilation was successful, and the message you get is only a warning? Or do you not have the binary now?

Wouter

**Comment by mdanzi** [comment]
Right, it looks like a warning, but no binary file gets created (at least not as far as I can find)

**Comment by wdecoster** [comment]
It should be at `target/release/STRdust` (assuming you compiled with `cargo build --release`)

**Comment by mdanzi** [comment]
Ah, so sorry about that! It is there. Thank you!

**Comment by wdecoster** [comment]
No problem! I should make a new release soon. Thanks for any feedback you might have :)
